import { useGLTF, Html, Sparkles } from '@react-three/drei'
import './Room.css'
import SmallScreen from './smallScreen/SmallScreen';

function Room() {
    const { nodes, materials } = useGLTF("/portfolio-finished.glb");

    return (
      <group dispose={null}>
        <Sparkles position={[-7.35, 3.5, -0.8]} color={'#facc15'} count={10} scale={[2, 2, 2]} size={4} speed={2} />
      <group position={[6.45, 0.64, 4.23]}>
        <primitive object={nodes.Bone} />
        <primitive object={nodes.Bone009} />
        <primitive object={nodes.Bone011} />
        <primitive object={nodes.Bone013} />
        <primitive object={nodes.Bone015} />
        <group position={[0.01, 0.02, 0.01]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008.geometry}
            material={materials.cat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008_1.geometry}
            material={materials.cateyes}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BigScreen.geometry}
        material={materials.Screen}
        position={[-2.18, 7.97, -0.21]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SmallScreen.geometry}
        material={materials.Screen}
        position={[0.79, 9.81, 8.56]}
        rotation={[1.57, 0, -0.95]}
        >
        <Html className="content-smallscreen" rotation-x={-Math.PI / 2} position={[0, 0.05, 0]} transform occlude>
          <SmallScreen />
        </Html>
      </mesh>
      <group position={[-4.22, 1.75, 11.27]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028.geometry}
          material={materials.Mashine}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_1.geometry}
          material={materials.Screen}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor.geometry}
        material={materials.Floor}
        position={[0.23, -0.06, 8.49]}
      />
      <group
        position={[1.5, 1.22, -0.82]}
        rotation={[-Math.PI, 1.35, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus001.geometry}
          material={materials["Wood.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus001_1.geometry}
          material={materials["TrainTracks.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus001_2.geometry}
          material={materials.Flag}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus001_3.geometry}
          material={materials.Screws}
        />
      </group>
      <group position={[-2.74, 3.06, -0.16]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026.geometry}
          material={materials.TrainTracks}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_1.geometry}
          material={materials.TrainTracks2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_2.geometry}
          material={materials.Bench}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_3.geometry}
          material={materials.DarkWood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_4.geometry}
          material={materials.Sign}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_5.geometry}
          material={materials.Lamp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_6.geometry}
          material={materials.Post}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_7.geometry}
          material={materials.Street}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_8.geometry}
          material={materials.Hedge}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_9.geometry}
          material={materials.Leaves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_10.geometry}
          material={materials.Soil}
        />
      </group>
      <group position={[-1.9, 5.62, 0.23]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials.Pipes}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials.Building}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_2.geometry}
          material={materials.StandTop}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_3.geometry}
          material={materials.Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_4.geometry}
          material={materials.DarkWood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_5.geometry}
          material={materials.Vents}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_6.geometry}
          material={materials.Blinds}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_7.geometry}
          material={materials.Boxes}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_8.geometry}
          material={materials.Sign}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_9.geometry}
          material={materials.Ele}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_10.geometry}
          material={materials.ScrennBorder}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_11.geometry}
          material={materials.Lamp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_12.geometry}
          material={materials.Post}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_13.geometry}
          material={materials.Ropes}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_14.geometry}
          material={materials.Stairs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_15.geometry}
          material={materials.Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_16.geometry}
          material={materials.Cups}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_17.geometry}
          material={materials.Bottle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_18.geometry}
          material={materials.Bottle2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_19.geometry}
          material={materials.Bottle4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_20.geometry}
          material={materials["Bottle3.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_21.geometry}
          material={materials.Mugs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_22.geometry}
          material={materials.Box}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_23.geometry}
          material={materials.Barrel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_24.geometry}
          material={materials.TextColor}
        />
      </group>
      <group
        position={[7.82, 2.61, -12.43]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text002.geometry}
          material={materials.TrainText}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text002_1.geometry}
          material={materials.Sign}
        />
      </group>
      <group
        position={[-0.5, -0.16, -8.03]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019.geometry}
          material={materials.Loco}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_2.geometry}
          material={materials.Screen3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_3.geometry}
          material={materials.Screen2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_4.geometry}
          material={materials["Screen.001"]}
        />
      </group>
    </group>
    );
}

export default Room